### ISSUE TITLE
REQUEST: Instant power in W, rather than kW 

### ISSUE THREAD

**Issue by PistolaPeteUK** [megakid/ha_hildebrand_glow_ihd_mqtt#9]
Hi There

Is there are easy way to change the output of the electricity meter from kW to W?
I can solve it temporarily with a template sensor, but would prefer to be able to switch it at source if possible.

Pete

**Comment by megakid** [comment]
It can't be done at the moment but this request is kind of similar to #3 with scaling support (but this one adds the requirement to change the units too)

**Comment by PistolaPeteUK** [comment]
No worries, if you don't ask - you don't get!
If you could keep it in the back of your mind,  it'd be appreciated

**Comment by ginkage** [comment]
`It can't be done at the moment`
But why? I've just created a PR that does just that — in fact, I've been using this patch for a while now, it works for me.

**Comment by megakid** [comment]
I didn't say it couldn't be done - just that it wasnt possible at the moment via UI or config flow.  Ofcourse people can edit the python directly and have a different unit.  Since not everyone wants Watts over Kilowatts I dont think I'll merge #12 as is.  Perhaps someone can add a config_flow setting to allow people to choose if they want Watts or Kilowatts
